package bomberman.mechanics.interfaces;

public enum EntityType {
    BOMBERMAN, DESTRUCTIBLE_WALL, UNDESTRUCTIBLE_WALL, BONUS_HEAL, BONUS_INCMAXHP, BONUS_INCMAXRANGE, BONUS_DECBOMBSPAWN, BONUS_DECBOMBFUSE, BONUS_INCSPEED, BONUS_MOREBOMBS, BOMB, BOMB_RAY
}
